//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweets
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Content { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
